from enum import Enum


class ProductVisibility(str, Enum):
    """Constants for filtering products by visibility in OZON API."""

    ALL = "ALL"
    VISIBLE = "VISIBLE"
    INVISIBLE = "INVISIBLE"
    EMPTY_STOCK = "EMPTY_STOCK"
    NOT_MODERATED = "NOT_MODERATED"
    MODERATED = "MODERATED"
    DISABLED = "DISABLED"
    STATE_FAILED = "STATE_FAILED"
    READY_TO_SUPPLY = "READY_TO_SUPPLY"
    VALIDATION_STATE_PENDING = "VALIDATION_STATE_PENDING"
    VALIDATION_STATE_FAIL = "VALIDATION_STATE_FAIL"
    VALIDATION_STATE_SUCCESS = "VALIDATION_STATE_SUCCESS"
    TO_SUPPLY = "TO_SUPPLY"
    IN_SALE = "IN_SALE"
    REMOVED_FROM_SALE = "REMOVED_FROM_SALE"
    OVERPRICED = "OVERPRICED"
    CRITICALLY_OVERPRICED = "CRITICALLY_OVERPRICED"
    EMPTY_BARCODE = "EMPTY_BARCODE"
    BARCODE_EXISTS = "BARCODE_EXISTS"
    QUARANTINE = "QUARANTINE"
    ARCHIVED = "ARCHIVED"
    OVERPRICED_WITH_STOCK = "OVERPRICED_WITH_STOCK"
    PARTIAL_APPROVED = "PARTIAL_APPROVED"


class RequestLimits(int, Enum):
    PRODUCT_LIST = 1000
    PRODUCT_INFO_LIST = 1000


class ExternalAPIUrls(str, Enum):
    BASE_URL = "https://api-seller.ozon.ru"
    PRODUCT_LIST = "/v3/product/list"
    PRODUCT_PRICE_LIST = "/v5/product/info/prices"
    PRODUCT_INFO_LIST = "/v3/product/info/list"
    PRODUCT_PRICE_UPDATE = "/v1/product/import/prices"
